name: Build and publish dev build for read db project

on:
  push:
    branches-ignore:
      - master
      - version-*
    paths-ignore:
      - README.md
      - LICENSE
      - .gitignore
jobs:
  grpc-version:
    name: Collect grpc version
    uses: th2-net/.github/.github/workflows/compound-prebuild-java-dev-workflow.yml@main
    with:
      project-path: grpc
  app-version:
    name: Collect app version
    uses: th2-net/.github/.github/workflows/compound-prebuild-java-dev-workflow.yml@main
    with:
      project-path: app
  build-and-publish-grpc-java:
    name: Build and publish Java gRPC distributions
    uses: th2-net/.github/.github/workflows/compaund-java-multi-project-build.yml@main
    with:
      projectPath: grpc
      additionalTasks: '["publish"]'
      release: false
    secrets:
      sonatypeUsername: ${{ secrets.SONATYPE_NEXUS_USERNAME }}
      sonatypePassword: ${{ secrets.SONATYPE_NEXUS_PASSWORD }}
      sonatypeSigningKey: ${{ secrets.SONATYPE_GPG_ARMORED_KEY }}
      sonatypeSigningPassword: ${{ secrets.SONATYPE_SIGNING_PASSWORD }}
  build-and-publish-grpc-python:
    name: Build and publish Python distributions to PyPI
    needs:
      - grpc-version
    uses: th2-net/.github/.github/workflows/compaund-python-grpc-pypi-publication.yml@main
    with:
      custom-version: ${{ needs.grpc-version.outputs.versionNumber }}.dev${{ github.run_id }}
      project-path: grpc
    secrets:
      pypi_password: ${{ secrets.PYPI_PASSWORD }}
  build-and-publish-core-java:
    name: Build and publish Java core distributions
    uses: th2-net/.github/.github/workflows/compaund-java-multi-project-build.yml@main
    with:
      projectPath: core
      additionalTasks: '["publish"]'
      release: false
    secrets:
      sonatypeUsername: ${{ secrets.SONATYPE_NEXUS_USERNAME }}
      sonatypePassword: ${{ secrets.SONATYPE_NEXUS_PASSWORD }}
      sonatypeSigningKey: ${{ secrets.SONATYPE_GPG_ARMORED_KEY }}
      sonatypeSigningPassword: ${{ secrets.SONATYPE_SIGNING_PASSWORD }}
  build-and-publish-oracle-extension-java:
    name: Build and publish Java oracle extension distributions
    uses: th2-net/.github/.github/workflows/compaund-java-multi-project-build.yml@main
    with:
      projectPath: oracle
      additionalTasks: '["publish"]'
      release: false
    secrets:
      sonatypeUsername: ${{ secrets.SONATYPE_NEXUS_USERNAME }}
      sonatypePassword: ${{ secrets.SONATYPE_NEXUS_PASSWORD }}
      sonatypeSigningKey: ${{ secrets.SONATYPE_GPG_ARMORED_KEY }}
      sonatypeSigningPassword: ${{ secrets.SONATYPE_SIGNING_PASSWORD }}
  owasp-scan:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: zulu
          java-version: 11
      - name: Validate Gradle Wrapper
        uses: gradle/actions/wrapper-validation@v4
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
        with:
          gradle-version: wrapper
          gradle-home-cache-includes: |
            caches
            notifications
            dependency-check-data
      - name: Gradle version
        run: ./gradlew --version
      - name: Run OWASP multi-project scanning
        run: ./gradlew dependencyCheckAggregate -PnvdApiKey=${{ secrets.NVD_APIKEY }}
      - name: Upload OWASP scan results to GitHub Security tab
        # dependabot does not have write access to publish scanning results (in any case we don't want that from temporal branches)
        if: (success() || failure()) && github.actor != 'dependabot[bot]'
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: './build/reports/dependency-check-report.sarif'
  license-scan:
    if: "!cancelled()"
    uses: th2-net/.github/.github/workflows/license_check.yml@main
    needs:
      - app-version
    with:
      version: ${{ needs.app-version.outputs.version }}
  publish-docker:
    name: Build docker image
    needs:
      - app-version
    uses: th2-net/.github/.github/workflows/compaund-java-docker-push.yml@main
    with:
      docker-username: ${{ github.actor }}
      version: ${{ needs.app-version.outputs.version }}
      versionNumber: ${{ needs.app-version.outputs.versionNumber }}
      dockerContext: '.'
      gradleProjectPath: 'app'
      gradleParameters: ${{ format('["clean", "build", "dockerPrepare", "-Pversion_suffix={0}"]', needs.app-version.outputs.versionSuffix) }}
    secrets:
      docker-password: ${{ secrets.GITHUB_TOKEN }}
  trivy-docker-scan:
    name: Scan Docker image for vulnerabilities
    needs:
      - publish-docker
      - app-version
    uses: th2-net/.github/.github/workflows/trivy-scan-github.yml@main
    with:
      image-path: ghcr.io/${{ github.repository }}:${{ needs.app-version.outputs.version }}
      target: 'os,library'
      sensitivity: 'CRITICAL,HIGH,MEDIUM'
