name: Build and publish read db project

on:
  push:
    branches:
      - master
      - version-*
    paths:
      - app/gradle.properties
      - grpc/gradle.properties
      - core/gradle.properties

jobs:
  changes:
    name: Collect changed files
    runs-on: ubuntu-20.04
    outputs:
      app: ${{ steps.filter.outputs.app }}
      grpc: ${{ steps.filter.outputs.grpc }}
      core: ${{ steps.filter.outputs.core }}
    steps:
      - uses: dorny/paths-filter@v2
        id: filter
        with:
          filters: |
            app:
              - 'app/gradle.properties'
            grpc:
              - 'grpc/gradle.properties'
            core:
              - 'core/gradle.properties'
  build-and-publish-grpc-java:
    name: Build and publish Java gRPC distributions
    needs:
      - changes
    if: ${{ needs.changes.outputs.grpc == 'true' }}
    uses: ./.github/workflows/build-and-publish-java.yml
    with:
      project-path: grpc
      release: true
    secrets: inherit
  build-and-publish-grpc-python:
    name: Build and publish Python distributions to PyPI
    needs:
      - changes
    if: ${{ needs.changes.outputs.grpc == 'true' }}
    uses: ./.github/workflows/build-and-publish-python.yml
    secrets: inherit
  build-and-publish-core-java:
    name: Build and publish Java core distributions
    needs:
      - changes
    if: ${{ needs.changes.outputs.core == 'true' }}
    uses: ./.github/workflows/build-and-publish-java.yml
    with:
      project-path: core
      release: true
    secrets: inherit
  publish-docker:
    name: Build and publish docker image
    runs-on: ubuntu-20.04
    if: |
      always() &&
      (needs.changes.outputs.app == 'true' || needs.changes.outputs.grpc == 'true' || needs.changes.outputs.core == 'true')
    needs:
      - build-and-publish-grpc-python
      - build-and-publish-grpc-java
      - build-and-publish-core-java
    steps:
      - uses: actions/checkout@v3
      - name: Read version from gradle.properties
        id: read_property
        uses: christian-draeger/read-properties@1.1.1
        with:
          path: app/gradle.properties
          properties: release_version
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
      - name: Build with Gradle
        run: ./gradlew -p app --info --warning-mode all clean build dockerPrepare
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - run: echo "REPOSITORY_NAME=$(echo '${{ github.repository }}' | awk -F '/' '{print $2}')" >> $GITHUB_OUTPUT
        id: meta
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v3
        with:
          push: true
          context: . # project dir
          tags: ghcr.io/${{ github.repository }}:${{ steps.read_property.outputs.release_version }}
          labels: com.exactpro.th2.${{ steps.meta.outputs.REPOSITORY_NAME }}=${{ steps.read_property.outputs.release_version }}