name: Build and publish read db project

on: workflow_dispatch

jobs:
  grpc-version:
    name: Extract grpc version
    uses: th2-net/.github/.github/workflows/compound-prebuild-java-workflow.yml@main
    with:
      project-path: grpc
  oracle-version:
    name: Extract app version
    uses: th2-net/.github/.github/workflows/compound-prebuild-java-workflow.yml@main
    with:
      project-path: oracle
  app-version:
    name: Extract app version
    uses: th2-net/.github/.github/workflows/compound-prebuild-java-workflow.yml@main
    with:
      project-path: app
  changes:
    name: Collect changed files
    runs-on: ubuntu-latest
    outputs:
      app: ${{ steps.filter.outputs.app }}
      grpc: ${{ steps.filter.outputs.grpc }}
      core: ${{ steps.filter.outputs.core }}
      oracle: ${{ steps.filter.outputs.oracle }}
    steps:
      - uses: dorny/paths-filter@v3
        id: filter
        with:
          filters: |
            app:
              - 'app/gradle.properties'
            grpc:
              - 'grpc/gradle.properties'
            core:
              - 'core/gradle.properties'
            oracle:
              - 'oracle/gradle.properties'
  build-and-publish-grpc-java:
    name: Build and publish Java gRPC distributions
    needs:
      - changes
    if: ${{ needs.changes.outputs.grpc == 'true' }}
    uses: th2-net/.github/.github/workflows/compaund-java-multi-project-build-release.yml@main
    with:
      projectPath: grpc
      release: true
      additionalTasks: '["publish"]'
    secrets:
      sonatypeUsername: ${{ secrets.SONATYPE_NEXUS_USERNAME }}
      sonatypePassword: ${{ secrets.SONATYPE_NEXUS_PASSWORD }}
      sonatypeSigningKey: ${{ secrets.SONATYPE_GPG_ARMORED_KEY }}
      sonatypeSigningPassword: ${{ secrets.SONATYPE_SIGNING_PASSWORD }}
  build-and-publish-grpc-python:
    name: Build and publish Python distributions to PyPI
    needs:
      - changes
    if: ${{ needs.changes.outputs.grpc == 'true' }}
    uses: th2-net/.github/.github/workflows/compaund-python-grpc-pypi-publication.yml@main
    with:
      project-path: grpc
    secrets:
      pypi_password: ${{ secrets.PYPI_PASSWORD }}
  build-and-publish-core-java:
    name: Build and publish Java core distributions
    needs:
      - changes
      - build-and-publish-grpc-java
    if: (needs.changes.outputs.core == 'true' || needs.changes.outputs.grpc == 'true') && !cancelled()
    uses: th2-net/.github/.github/workflows/compaund-java-multi-project-build-release.yml@main
    with:
      projectPath: core
      release: true
      additionalTasks: '["publish"]'
    secrets:
      sonatypeUsername: ${{ secrets.SONATYPE_NEXUS_USERNAME }}
      sonatypePassword: ${{ secrets.SONATYPE_NEXUS_PASSWORD }}
      sonatypeSigningKey: ${{ secrets.SONATYPE_GPG_ARMORED_KEY }}
      sonatypeSigningPassword: ${{ secrets.SONATYPE_SIGNING_PASSWORD }}
  build-and-publish-oracle-extension-java:
    name: Build and publish Java oracle extension distributions
    needs:
      - changes
      - build-and-publish-core-java
    if: ${{ needs.changes.outputs.oracle == 'true' }}
    uses: th2-net/.github/.github/workflows/compaund-java-multi-project-build-release.yml@main
    with:
      projectPath: oracle
      release: true
      additionalTasks: '["publish"]'
    secrets:
      sonatypeUsername: ${{ secrets.SONATYPE_NEXUS_USERNAME }}
      sonatypePassword: ${{ secrets.SONATYPE_NEXUS_PASSWORD }}
      sonatypeSigningKey: ${{ secrets.SONATYPE_GPG_ARMORED_KEY }}
      sonatypeSigningPassword: ${{ secrets.SONATYPE_SIGNING_PASSWORD }}
  owasp-scan:
    if: "!cancelled()"
    uses: th2-net/.github/.github/workflows/owasp-gradle-scan.yml@main
    secrets:
      nvd-api-key: ${{ secrets.NVD_APIKEY }}
      oss-index-user: ${{ secrets.OSSINDEX_SONATYPE_USER }}
      oss-index-token: ${{ secrets.OSSINDEX_SONATYPE_TOKEN }}
      cisa-domain: ${{ secrets.CISA_DOMAIN }}
      cisa-user: ${{ secrets.CISA_USER }}
      cisa-password: ${{ secrets.CISA_PWD }}
  license-scan:
    if: "!cancelled()"
    uses: th2-net/.github/.github/workflows/license_check.yml@main
    needs:
      - app-version
    with:
      version: ${{ needs.app-version.outputs.version }}
  publish-docker:
    name: Build and publish docker image
    if: |
      (needs.changes.outputs.app == 'true' || needs.changes.outputs.grpc == 'true' || needs.changes.outputs.core == 'true' || needs.changes.outputs.oracle == 'true')
      && !cancelled()
    needs:
      - build-and-publish-grpc-python
      - build-and-publish-grpc-java
      - build-and-publish-core-java
      - build-and-publish-oracle-extension-java
      - app-version
    uses: th2-net/.github/.github/workflows/compaund-java-docker-push.yml@main
    with:
      docker-username: ${{ github.actor }}
      version: ${{ needs.app-version.outputs.version }}
      versionNumber: ${{ needs.app-version.outputs.version }}
      dockerContext: '.'
      gradleProjectPath: 'app'
      gradleParameters: '["clean", "build", "dockerPrepare"]'
    secrets:
      docker-password: ${{ secrets.GITHUB_TOKEN }}
  trivy-docker-scan:
    name: Scan Docker image for vulnerabilities
    if: needs.publish-docker.result == 'success' && !cancelled()
    needs:
      - publish-docker
      - app-version
    uses: th2-net/.github/.github/workflows/trivy-scan-github.yml@main
    with:
      image-path: ghcr.io/${{ github.repository }}:${{ needs.app-version.outputs.version }}
      target: 'os,library'
      sensitivity: 'CRITICAL,HIGH,MEDIUM'
  create-grpc-tag:
    if: needs.build-and-publish-grpc-java.result == 'success' && needs.build-and-publish-grpc-python.result == 'success' && !cancelled()
    name: Create and push gRPC tag
    needs: [ grpc-version, build-and-publish-grpc-java, build-and-publish-grpc-python ]
    uses: th2-net/.github/.github/workflows/compaund-git-tag-push.yml@main
    with:
      tagName: ${{ needs.grpc-version.outputs.version }}-grpc
  create-oracle-tag:
    if: needs.build-and-publish-oracle-extension-java.result == 'success' && !cancelled()
    name: Create and push oracle extension tag
    needs: [ oracle-version, build-and-publish-oracle-extension-java ]
    uses: th2-net/.github/.github/workflows/compaund-git-tag-push.yml@main
    with:
      tagName: ${{ needs.oracle-version.outputs.version }}-oracle
  create-app-tag:
    if: needs.publish-docker.result == 'success' && needs.build-and-publish-core-java.result == 'success' && !cancelled()
    name: Create and push app tag
    needs: [ app-version, publish-docker, build-and-publish-core-java ]
    uses: th2-net/.github/.github/workflows/compaund-git-tag-push.yml@main
    with:
      tagName: ${{ needs.app-version.outputs.version }}