name: Build and publish read db project

on:
  push:
    branches:
      - master
      - version-*
    paths:
      - app/gradle.properties
      - grpc/gradle.properties
      - core/gradle.properties

jobs:
  versions:
    name: Extract app version
    runs-on: ubuntu-20.04
    outputs:
      app-version: ${{ steps.read_property.outputs.release_version }}
    steps:
      - uses: actions/checkout@v3
      - name: Read version from gradle.properties
        id: read_property
        uses: christian-draeger/read-properties@1.1.1
        with:
          path: app/gradle.properties
          properties: release_version
  changes:
    name: Collect changed files
    runs-on: ubuntu-20.04
    outputs:
      app: ${{ steps.filter.outputs.app }}
      grpc: ${{ steps.filter.outputs.grpc }}
      core: ${{ steps.filter.outputs.core }}
    steps:
      - uses: dorny/paths-filter@v2
        id: filter
        with:
          filters: |
            app:
              - 'app/gradle.properties'
            grpc:
              - 'grpc/gradle.properties'
            core:
              - 'core/gradle.properties'
  build-and-publish-grpc-java:
    name: Build and publish Java gRPC distributions
    needs:
      - changes
    if: ${{ needs.changes.outputs.grpc == 'true' }}
    uses: th2-net/.github/.github/workflows/compaund-java-multi-project-build.yml@multi-project-workflows
    with:
      projectPath: grpc
      additionalTasks: '["publish"]'
    secrets:
      sonatypeUsername: ${{ secrets.SONATYPE_NEXUS_USERNAME }}
      sonatypePassword: ${{ secrets.SONATYPE_NEXUS_PASSWORD }}
      sonatypeSigningKey: ${{ secrets.SONATYPE_GPG_ARMORED_KEY }}
      sonatypeSigningPassword: ${{ secrets.SONATYPE_SIGNING_PASSWORD }}
  build-and-publish-grpc-python:
    name: Build and publish Python distributions to PyPI
    needs:
      - changes
    if: ${{ needs.changes.outputs.grpc == 'true' }}
    uses: ./.github/workflows/build-and-publish-python.yml
    secrets: inherit
  build-and-publish-core-java:
    name: Build and publish Java core distributions
    needs:
      - changes
      - build-and-publish-grpc-java
    if: ${{ needs.changes.outputs.core == 'true' }}
    uses: th2-net/.github/.github/workflows/compaund-java-multi-project-build.yml@multi-project-workflows
    with:
      projectPath: core
      additionalTasks: '["publish"]'
    secrets:
      sonatypeUsername: ${{ secrets.SONATYPE_NEXUS_USERNAME }}
      sonatypePassword: ${{ secrets.SONATYPE_NEXUS_PASSWORD }}
      sonatypeSigningKey: ${{ secrets.SONATYPE_GPG_ARMORED_KEY }}
      sonatypeSigningPassword: ${{ secrets.SONATYPE_SIGNING_PASSWORD }}
  owasp-scan:
    needs:
      - build-and-publish-core-java
    uses: th2-net/.github/.github/workflows/owasp-gradle-scan.yml@main
    with:
      multiproject: true
  publish-docker:
    name: Build and publish docker image
    if: |
      always() &&
      (needs.changes.outputs.app == 'true' || needs.changes.outputs.grpc == 'true' || needs.changes.outputs.core == 'true')
    needs:
      - build-and-publish-grpc-python
      - build-and-publish-grpc-java
      - build-and-publish-core-java
      - versions
    uses: th2-net/.github/.github/workflows/compaund-java-docker-push.yml@docker-gradle
    with:
      docker-username: ${{ github.actor }}
      version: ${{ needs.versions.outputs.app-version }}
      versionNumber: ${{ needs.versions.outputs.app-version }}
      dockerContext: '.'
      gradleProjectPath: 'app'
      gradleParameters: '["clean", "build", "dockerPrepare"]'
    secrets:
      docker-password: ${{ secrets.GITHUB_TOKEN }}
  trivy-docker-scan:
    name: Scan Docker image for vulnerabilities
    needs:
      - publish-docker
      - versions
    uses: th2-net/.github/.github/workflows/trivy-scan-github.yml@main
    with:
      image-path: ghcr.io/${{ github.repository }}:${{ needs.versions.outputs.app-version }}
      target: 'os,library'
      sensitivity: 'CRITICAL,HIGH,MEDIUM'